language: python
python: 2.7
env:
 - TOX_ENV=py27-django1.7
 - TOX_ENV=py27-django1.8
 - TOX_ENV=py27-django1.9
 - TOX_ENV=docs
 - TOX_ENV=flake8
install:
 - pip install tox
script:
 - tox -e $TOX_ENV